# Configuration variables

[github]
# Proposal repository
repo = "matrix-org/matrix-doc"
# Github bot user token
token = ""
# Labels involved in the MSC process
labels = ["proposal",
          "proposal-in-review",
          "proposed-final-comment-period",
          "final-comment-period",
          "finished-final-comment-period",
          "spec-pr-missing",
          "spec-pr-in-review",
          "merged"]

# Github username to Matrix user id mappings
# Allows the bot to ping people when they need to approve FCP
[user_ids]
someone = "@someone:example.com"

[mscbot]
# MSCBot web server (https://github.com/matrix-org/mscbot)
url = "https://mscbot.amorgan.xyz"

[matrix]
# Bot user ID
user_id = "@mscbot:matrix.org"
# Bot access token
token = ""
# Interval between /sync requests.
sync_interval = 5
# Type of message the bot should send to rooms
# Note that only "m.room.message" will notify Riot users
message_type = "m.room.message"

[bot]
# Room-specific data file path
data_filepath = "./room_data.json"
# Bot command (Ex. "mscbot" means a user would write "mscbot: show all")
command = "mscbot"
# Default daily summary time (UTC). Can be configured or disabled per-room.
daily_summary_time = "07:00"

[msc]
# Duration of a final comment period in days
fcp_length = 5

[logging]
# Logging level. "INFO" for default, "DEBUG" for debug logs
level = "INFO"
# Optional logfile. If set, logs will not be printed to stdout
#logfile = "mscbot.log"