# Configuration variables

[github]
# Proposal repository
repo = "matrix-org/matrix-doc"
# Github bot user token
token = ""

[mscbot]
# MSCBot web server (https://github.com/matrix-org/mscbot)
url = "https://mscbot.amorgan.xyz"

[matrix]
# Bot user ID
user_id = "@mscbot:matrix.org"
# Bot token
token = ""

[bot]
# Print a daily summary at this time. Time in UTC
daily_summary_time = "07:00"
# Optional list of priority MSC IDs. ONLY these will be shown
#priority_mscs = [1693, 1759]
# Optional list of remaining MSCs. Requires priority_mscs to be defined
#msc_goal = 5

[msc]
# Duration of a final comment period
fcp_length = 5

[logging]
# Logging level. "INFO" for default, "DEBUG" for debug logs
level = "INFO"
# Optional logfile. If set logs will not be printed to stdout
#logfile = "mscbot.log"